name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fetch Dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
        env:
          YBM_ALLOWLIST_PREFIX: ${{ secrets.YBM_ALLOWLIST_PREFIX }}
          YBM_API_KEY: ${{ secrets.YBM_API_KEY }}
          YBM_ACCOUNT_ID: ${{ secrets.YBM_ACCOUNT_ID }}
          YBM_CLUSTER_ID: ${{ secrets.YBM_CLUSTER_ID }}
          YBM_ENDPOINT: ${{ secrets.YBM_ENDPOINT }}
          YBM_PROJECT_ID: ${{ secrets.YBM_PROJECT_ID }}
