name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # workflow_run:
  #     workflows: [Build]
  #     types:
  #       - completed

jobs:
  release:
    name: Create Release
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Changelog
        id: changelogs-builder
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          prerelease: false
          draft: true
          generate_release_notes: true
          append_body: true
          body: ${{steps.changelog-builder.outputs.changelog}}

